### ISSUE TITLE
Getting nothing when i use the same with polygon

### ISSUE THREAD

**Issue by yaswanthkata** [teropa/metabubbles#2]
import { Component } from '@angular/core';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {

 public sdspolygons;
  ngOnInit() {
    this.sdspolygons = [
    {points:"150,75 258,137.5 258,262.5 150,325 42,262.6 42,137.5"},
  ];
  }

  ngOnDestroy() {
  }

  onAnimationFrame() {
  }
}

@Component({
  selector: '[a-polygon]',
  template: `
     <svg:polygon points="200,10 250,190 160,210"></svg:polygon>
`
})
export class PolygonComponent {
}

app.component.html

 <svg viewBox="0 0 900 500"
       preserveAspectRatio="xMidYMid meet">
         <svg:g a-polygon
             *ngFor="let polygon of sdspolygons">
             /svg:g
  </svg>

Im not able to figure what is missing .Could you please help me .

**Comment by teropa** [comment]
Sorry, I can't make out from this code what the problem is. Can you share your whole repository on GitHub so that I can see the whole thing?

**Comment by yaswanthkata** [comment]
@teropa  Could you please update your existing repository to angular 2 latest version and try it.i tried your repo with the latest angular2 the svg is not rendering anything.

**Comment by teropa** [comment]
Unfortunately I'm not going to have time to do that any time soon. But I can take a look at your version if you can share it.

**Comment by yaswanthkata** [comment]
@teropa  you can mark this  as closed as i developed a library for svg  https://www.npmjs.com/package/angular-svg
